env = Environment()
env.Tool('runExternalCommand')

params = Variables(['../custom.py'])
params.Add(BoolVariable('with_debug', 'Build with debug symbols for GDB usage', False))
params.Update(env)

if env['with_debug']:
	env.Append(CXXFLAGS=['-g'])

env.Append(LINKFLAGS=['-static'])

sources = []
sources.append('src/Launcher.cpp')
sources.append('src/LauncherIni.cpp')
sources.append('src/String.cpp')
sources.append('src/File.cpp')
sources.append('src/Exception.cpp')

def stripBuild(target, source, env):
	src = source[0].abspath
	trg = target[0].abspath
	
	script = []
	script.append('cp "{}" "{}" || exit 1'.format(src, trg))
	script.append('strip "{}" || exit 1'.format(trg))
	if not env.RunExternalCommand(script):
		raise Exception('Failed running script')

if env['with_debug']:
	app = env.Program('launcher64', sources)
	
else:
	temp = env.Program('launcher64_temp', sources)
	app = env.Command('launcher64', temp, env.Action(stripBuild, 'Strip $TARGET'))

Default(app)
