name: Build Linux

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          submodules: 'recursive'
      
      - name: Install required packages
        run: |
          sudo apt -y install build-essential scons
      
      - name: Build
        run: scons
      
      - name: Store Archives
        uses: actions/upload-artifact@v3
        with:
          name: archive-linux
          path: |
            linux/build/launcher64
          if-no-files-found: error
