name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        required: true
        type: string
        default: 'X.Y{.Z}'
  repository_dispatch:

jobs:
  build_linux:
    uses: ./.github/workflows/build_linux.yml
    with:
      artifactArchive: archives-linux
    
  build_windows:
    uses: ./.github/workflows/build_windows.yml
    with:
      artifactArchive: archives-windows
    
  build_windows_direct:
    uses: ./.github/workflows/build_windows_direct.yml
    with:
      artifactArchive: archives-windows-direct

  build:
    runs-on: ubuntu-latest
    needs: [build_linux, build_windows, build_windows_direct]
    
    env:
      version: ${{ github.event.client_payload.version && github.event.client_payload.version || github.event.inputs.version }}
      
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: 'recursive'
      
      - name: Install required packages
        run: |
          sudo apt -y install build-essential scons
      
      - name: Get Linux Archives
        uses: actions/download-artifact@v4
        with:
          name: archives-linux
          path: linux/build
      
      - name: Get Windows Archives
        uses: actions/download-artifact@v4
        with:
          name: archives-windows
          path: windows/build
      
      - name: Get Windows Direct Archives
        uses: actions/download-artifact@v4
        with:
          name: archives-windows-direct
          path: windows_direct/build
      
      - name: Build
        run: scons version=${{ env.version }}
      
      - name: Upload Artifacts
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: false
          artifactErrorsFailBuild: true
          draft: false
          prerelease: false
          commit: 'main'
          tag: 'v${{ env.version }}'
          name: 'Distribute DELGA ${{ env.version }}'
          body: |
            Distribute DELGA files for projects based on Drag[en]gine Version ${{ env.version }} . See included README.md on instructions on how to use the distribution files.
          artifacts: build/distribution/distribute-delga-${{ env.version }}.zip
