name: TestBuild

on:
  workflow_dispatch:

jobs:
  build_linux:
    uses: ./.github/workflows/build_linux.yml
    with:
      artifactArchive: archives-linux
    
  build_windows:
    uses: ./.github/workflows/build_windows.yml
    with:
      artifactArchive: archives-windows
    
  build_windows_direct:
    uses: ./.github/workflows/build_windows_direct.yml
    with:
      artifactArchive: archives-windows-direct

  build_android:
    uses: ./.github/workflows/build_android.yml
    with:
      artifactArchive: archives-android
    
  build:
    runs-on: ubuntu-latest
    needs: [build_linux,
        build_windows,
        build_windows_direct,
        build_android]
    
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: 'recursive'
      
      - name: Install required packages
        run: |
          sudo apt -y install build-essential scons
      
      - name: Get Linux Archives
        uses: actions/download-artifact@v4
        with:
          name: archives-linux
          path: linux/build
      
      - name: Get Windows Archives
        uses: actions/download-artifact@v4
        with:
          name: archives-windows
          path: windows/build
      
      - name: Get Windows Direct Archives
        uses: actions/download-artifact@v4
        with:
          name: archives-windows-direct
          path: windows_direct/build
      
      - name: Get Android Archives
        uses: actions/download-artifact@v4
        with:
          name: archives-android
          path: android/build
      
      - name: Build
        run: scons version=9999
      
      - name: Store Archives
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifactArchive }}
          path: build/distribution/distribute-delga-9999.zip
          if-no-files-found: error
